name: "binix-action"
author: "krezh"
description: "Cache Nix derivations with Binix"

branding:
  icon: "layers"
  color: "purple"

inputs:
  endpoint:
    description: "Binix endpoint"
    required: true
  cache:
    description: "Binix cache name"
    required: true
  inputs-from:
    description: "Path to get the Nixpkgs flake input from instead of `github:krezh/binix`"
    required: false
  include-paths:
    description: "Regular expressions for matching paths to include when pushing (delimited by newlines)"
    required: false
  exclude-paths:
    description: "Regular expressions for matching paths to exclude when pushing (delimited by newlines)"
    required: false
  skip-push:
    description: "Disable pushing to the cache automatically"
    required: false
  token:
    description: "Binix authorization token"
    required: false
  skip-use:
    description: "Set to true to skip using Binix cache as a substituter"
    required: false

runs:
  using: "node24"
  main: "dist/index.js"
  post: "dist/index.js"
